# Use the same base image as your Django app
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only the dependencies to leverage Docker's layer caching
COPY nanpy /modules/napy
COPY backend/requirements.txt /app/

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django project into the container
COPY backend /app

# Set the environment variable for Django settings
ENV DJANGO_SETTINGS_MODULE=dyhealthnet_project.settings

# Add the /app directory to PYTHONPATH
ENV PYTHONPATH="/modules:${PYTHONPATH}"

# Default command for the Celery worker
CMD ["celery", "-A", "dyhealthnet_project", "worker", "--loglevel=info"]

