# Generated by Django 5.0.4 on 2024-05-06 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Edges",
            new_name="Edge",
        ),
        migrations.RenameModel(
            old_name="Nodes",
            new_name="Node",
        ),
    ]
