# Generated by Django 5.0.4 on 2024-05-06 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_rename_edges_edge_rename_nodes_node"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
