# Generated by Django 4.1.3 on 2024-07-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisorderAssociatesPhenotypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'disorder_associates_phenotypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disorders',
            fields=[
                ('mondo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'disorders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsDisorderDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_disorder_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsMetaboliteDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_metabolite_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsMetaboliteMetabolite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_metabolite_metabolite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsMetabolitePhenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_metabolite_phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsPhenotypeDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_phenotype_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsPhenotypePhenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_phenotype_phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsProteinDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_protein_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsProteinMetabolite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_protein_metabolite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsProteinPhenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_protein_phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectsProteinProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('adjusted_p_value', models.FloatField(blank=True, null=True)),
                ('effect_size', models.FloatField(blank=True, null=True)),
                ('effect_size_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'effects_protein_protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneAssociatesDisorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'gene_associates_disorders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genes',
            fields=[
                ('entrez_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'genes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaboliteAssociatesDisorders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'metabolite_associates_disorders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolites',
            fields=[
                ('hmdb_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'metabolites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phenotypes',
            fields=[
                ('hpo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'phenotypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProteinAssociatesMetabolites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'protein_associates_metabolites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProteinAssociatesProteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'protein_associates_proteins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proteins',
            fields=[
                ('uniprot_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('sequence', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_entrez_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'proteins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewDescriptionFTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'view_description_fts',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='edge',
            old_name='score',
            new_name='pval',
        ),
        migrations.AddField(
            model_name='edge',
            name='effect_size_type',
            field=models.CharField(default='undefined', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edge',
            name='pval_adj',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
