# Generated by Django 4.1.3 on 2024-07-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_disorderassociatesphenotypes_disorders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortMetabolite',
            fields=[
                ('cohort_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cohort_metabolite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CohortPhenotype',
            fields=[
                ('cohort_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cohort_phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CohortProtein',
            fields=[
                ('cohort_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cohort_protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('mondo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisorderAssociatesPhenotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'disorder_associates_phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('entrez_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'gene',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneAssociatesDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'gene_associates_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenomicVariant',
            fields=[
                ('variant_primarydomainid', models.CharField(db_column='variant_primaryDomainId', max_length=200, primary_key=True, serialize=False)),
                ('alternativesequence', models.CharField(blank=True, db_column='alternativeSequence', max_length=200, null=True)),
                ('chromosome', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.CharField(blank=True, max_length=200, null=True)),
                ('datasources', models.CharField(blank=True, db_column='dataSources', max_length=200, null=True)),
                ('domainids', models.CharField(blank=True, db_column='domainIds', max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('referencesequence', models.CharField(blank=True, db_column='referenceSequence', max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('varianttype', models.CharField(blank=True, db_column='variantType', max_length=200, null=True)),
            ],
            options={
                'db_table': 'genomic_variant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metabolite',
            fields=[
                ('hmdb_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'metabolite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetaboliteAssociatesDisorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'metabolite_associates_disorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('hpo_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('xrefs', models.TextField(blank=True, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'phenotype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('uniprot_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sequence', models.CharField(blank=True, max_length=200, null=True)),
                ('gene_entrez_id', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('observation_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProteinAssociatesMetabolite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_source', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'protein_associates_metabolite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProteinAssociatesProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'protein_associates_protein',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariantAffectsGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'variant_affects_gene',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DisorderAssociatesPhenotypes',
        ),
        migrations.DeleteModel(
            name='Disorders',
        ),
        migrations.DeleteModel(
            name='EffectsDisorderDisorder',
        ),
        migrations.DeleteModel(
            name='EffectsMetaboliteDisorder',
        ),
        migrations.DeleteModel(
            name='EffectsPhenotypeDisorder',
        ),
        migrations.DeleteModel(
            name='EffectsProteinDisorder',
        ),
        migrations.DeleteModel(
            name='GeneAssociatesDisorders',
        ),
        migrations.DeleteModel(
            name='Genes',
        ),
        migrations.DeleteModel(
            name='MetaboliteAssociatesDisorders',
        ),
        migrations.DeleteModel(
            name='Metabolites',
        ),
        migrations.DeleteModel(
            name='Phenotypes',
        ),
        migrations.DeleteModel(
            name='ProteinAssociatesMetabolites',
        ),
        migrations.DeleteModel(
            name='ProteinAssociatesProteins',
        ),
        migrations.DeleteModel(
            name='Proteins',
        ),
    ]
