"""
Django settings for dyhealthnet_project project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ
from celery import Celery

env = environ.Env(
    DEBUG=(bool, False),
    NUM_WORKERS=(int, 1),
    LOW_MEMORY=(bool, True),
    DROP_INSIGNIFICANT_EDGES=(bool, False),
    MAX_CONTEXT_PER_USER=(int, 5),
    PRESERVE_PRIVACY=(bool, True),
    CRITICAL_NUMBER=(int, 10),
    NO_CACHE=(bool, False),
    REDIS_URL=(str, 'localhost:6379'),
)
environ.Env.read_env()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

FRONTEND_HOME_URL = env('FRONTEND_HOME_URL')

ALLOWED_HOSTS = ['*']

SITE_ID = 1 # Django’s Sites framework is required for django-allauth

# Application definition

INSTALLED_APPS = [
    'network.apps.NetworksConfig',
    'django.contrib.admin', #
    'django.contrib.auth', #
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django_extensions', # optional show_urls
    # Added for OpenAPI
    'drf_spectacular',
    'rest_framework',
    # Third-party apps
    'corsheaders',
    # django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
]

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        # For each OAuth based provider, either add a ''SocialApp''
        # (''socialaccount'' app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': 'Iv23liAv6MBm8L4qyxpO',  # TODO to do this correctly for a user app?
            'secret': 'e9a34c4966ad6eb051e32fd101f623681f160209',
            'key': ''
        },
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,  # Optional, enables PKCE (Proof Key for Code Exchange)
        'SCOPE': ['user', 'email', 'user:email'] ,
    },
    'orcid': {
        # For each OAuth based provider, either add a ''SocialApp''
        # (''socialaccount'' app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '<your_client_id>',
            'secret': '',
            'key': ''
        },
        'SCOPE': ['user', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'OAUTH_PKCE_ENABLED': True,  # Enable PKCE for additional security
    }
}
#ACCOUNT_AUTHENTICATION_METHOD = "username_email"
#SOCIALACCOUNT_ADAPTER = "network.adapter.MySocialAccountAdapter"
#ACCOUNT_ADAPTER = 'network.adapter.MyAccountAdapter'
#SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',          # Default authentication
    'allauth.account.auth_backends.AuthenticationBackend', # Allauth authentication
]

# Added for OpenAPI
REST_FRAMEWORK = {
    # your other DRF settings here
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'DyHealthNet API',
    'DESCRIPTION': 'API documentation',
    'VERSION': '1.0.0',
    'SERVERS': [{
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'http://localhost:9999',
            'description': 'Development server 2'
        }]
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # Manages sessions across requests
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Associates users with requests using sessions.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow specific origins
CORS_ALLOWED_ORIGINS = [
    FRONTEND_HOME_URL,  # Frontend URL  #TODO adapt if necessary
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    FRONTEND_HOME_URL,  # Frontend URL
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600 # 1h

ROOT_URLCONF = 'dyhealthnet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dyhealthnet_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME':  env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASS"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}


# Password validation, Password requirements
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Redirect URLs after login/logout
LOGIN_REDIRECT_URL = FRONTEND_HOME_URL
LOGOUT_REDIRECT_URL = FRONTEND_HOME_URL


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True  # TODO set to false in production

TEST_RUNNER = 'django.test.runner.DiscoverRunner'

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
            'datefmt': '%d/%b/%Y %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'network': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': True,
        }
    },
}

# Redis settings

REDIS_URL = env('REDIS_URL')

CELERY_BROKER_URL = f'redis://{REDIS_URL}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_URL}/0'

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{REDIS_URL}/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


# Custom DyHealthNet settings
INPUT_FILES = {
    'proteins': {
        'path': env("PROTEIN_PATH"),
        'meta': env("PROTEIN_META_PATH"),
        'label': env("PROTEIN_LABEL_COLUMN"),
        'description': env("PROTEIN_DESCRIPTION_COLUMN"),
    },
    'phenotypes': {
        'path': env("PHENOTYPE_PATH"),
        'meta': env("PHENOTYPE_META_PATH"),
        'label': env("PHENOTYPE_LABEL_COLUMN"),
        'description': env("PHENOTYPE_DESCRIPTION_COLUMN"),
        'type': env("PHENOTYPE_TYPE_COLUMN"),
    },
    'metabolites': {
        'path': env("METABOLITE_PATH"),
    },
    'edges': {
        'path': env("CALCULATED_EDGES_PATH"),
    },
    'labels': {
        'path': env('VAR_LABEL_MAPPING')
    }
}
PATIENT_ID_COLUMN = env("PATIENT_ID_COLUMN")


NAN_VALUE = -999.0
ALPHA = 0.05
DROP_INSIGNIFICANT = env("DROP_INSIGNIFICANT_EDGES", cast=bool)

NUM_WORKERS = env("NUMBER_OF_WORKERS", cast=int)
LOW_MEMORY = env("LOW_MEMORY", cast=bool)
MAX_CONTEXT_PER_USER = env("MAX_CONTEXT_PER_USER", cast=int)
PRESERVE_PRIVACY = env("PRESERVE_PRIVACY", cast=bool)
CRITICAL_NUMBER = env("CRITICAL_NUMBER", cast=int)
NO_CACHE = env("NO_CACHE", cast=bool)


# TODO add real email functionality
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_FILE_PATH = BASE_DIR / 'emails'
